language: android
sudo: true
android:
  components:
  - build-tools-23.0.1
  - android-23
  - extra-android-m2repository
  - extra-android-support
before_install:
#- openssl aes-256-cbc -K $encrypted_c2b3cee57976_key -iv $encrypted_c2b3cee57976_iv
#  -in finder.jks.enc -out app/finder.jks -d
- gem install fir-cli
script:
- "./gradlew assembleRelease"
