language: android
sudo: false
android:
  components:
  - build-tools-23.0.1
  - android-23
  - extra-android-m2repository
  - extra-android-support
before_install:
- openssl aes-256-cbc -K $encrypted_e41864bb9dab_key -iv $encrypted_e41864bb9dab_iv
  -in app/finder.jks.enc -out app/finder.jks -d
- gem install fir-cli
script:
- "./gradlew assembleRelease"
